### ISSUE TITLE
Portable files

### ISSUE THREAD

**Issue by AlesRFK** [Fuhrmann/keypirinha-sharex#1]
Hello I have a small problem. 
I am using ShareX.paf version with this settup
```
[main]
path = %UserProfile%\Home\Tools\_PApps\PortableApps\ShareXPortable\App\ShareX
user_path = %UserProfile%\Home\Tools\_PApps\PortableApps\ShareXPortable\Data
```
Can you tell me what the plugin looking for? For directory or *.exe, *.json?

> FileNotFoundError('file not found: "{}" (initial path: "{}")'.format(thing, initial_thing))

This looks like that it doesnt even pick up that settings ... Iam noob tho
Thank you :)

**Comment by Fuhrmann** [comment]
Hello @AlennGK! It searches for the file `HotkeysConfig.json` in the `user_path` directory!

The default `user_path` directory as you can see in the [share.ini](https://github.com/Fuhrmann/keypirinha-sharex/blob/master/src/sharex.ini) file is: 

`# * Default: "C:\Users\YOUR_USER\Documents\ShareX"`

But since you changed that, this plugin will search this file in:

`%UserProfile%\Home\Tools\_PApps\PortableApps\ShareXPortable\Data\HotkeysConfig.json`

Maybe your ShareXPortable installation doesn't have this file? Let me know!

**Comment by Fuhrmann** [comment]
What I explained above is what this plugin do to load your custom workflows. To load the actions displayed in the README file of this plugin, it loads the `actions.json` file that is shipped with the plugin: https://github.com/Fuhrmann/keypirinha-sharex/blob/master/src/actions.json

This is the only error indicated by Keypirinha's window console?

**Comment by AlesRFK** [comment]
Problem is with the 
`ERROR: Error from ShareX.ShareX.on_execute:`
I have tried both .exe files in the project.
[Files.txt](https://github.com/Fuhrmann/keypirinha-sharex/files/2837755/Files.txt)

**Comment by Fuhrmann** [comment]
Is you still having the problem? I'm not using windows at this moment so I couldn't debug this error. Can you paste here the log or something from Keypirinha? Thanks!

**Comment by trash-panda-v91-beta** [comment]
Hey,

I encountered same problem. I'm using portable version of ShareX and when I wanted to change default ShareX location, it didn't work. 

I checked sharex.py and found problem with passing quotes between your script and ini file. You're using `settings.get()` in function `read_config(self)` but you should use `settings.get_stripped()`. 

Edited function looks like this:
```python
    def read_config(self):
        settings = self.load_settings()
        self.sharex_path = settings.get_stripped("path", "main", self.DEFAULT_SHAREX_PATH)

        if not self.file_exists("{}\{}".format(self.sharex_path, self.SHAREX_EXE)):
            self.err("Could not find ShareX executable in the provided path: ", self.sharex_path)

        self.sharex_userpath = settings.get_stripped("user_path", "main", self.DEFAULT_SHAREXUSER_PATH)  
```

**Comment by sorashadow** [comment]
> Hey,
> 
> I encountered same problem. I'm using portable version of ShareX and when I wanted to change default ShareX location, it didn't work.
> 
> I checked sharex.py and found problem with passing quotes between your script and ini file. You're using `settings.get()` in function `read_config(self)` but you should use `settings.get_stripped()`.
> 
> Edited function looks like this:
> 
> ```python
>     def read_config(self):
>         settings = self.load_settings()
>         self.sharex_path = settings.get_stripped("path", "main", self.DEFAULT_SHAREX_PATH)
> 
>         if not self.file_exists("{}\{}".format(self.sharex_path, self.SHAREX_EXE)):
>             self.err("Could not find ShareX executable in the provided path: ", self.sharex_path)
> 
>         self.sharex_userpath = settings.get_stripped("user_path", "main", self.DEFAULT_SHAREXUSER_PATH)  
> ```

I can confirm that modification is successful - I directly modified de _py_ inside keypirinha package, and it works. @Fuhrmann, could you update the project? If you want, we can create a pull request for you.

**Comment by Fuhrmann** [comment]
> > Hey,
> > I encountered same problem. I'm using portable version of ShareX and when I wanted to change default ShareX location, it didn't work.
> > I checked sharex.py and found problem with passing quotes between your script and ini file. You're using `settings.get()` in function `read_config(self)` but you should use `settings.get_stripped()`.
> > Edited function looks like this:
> > ```python
> >     def read_config(self):
> >         settings = self.load_settings()
> >         self.sharex_path = settings.get_stripped("path", "main", self.DEFAULT_SHAREX_PATH)
> > 
> >         if not self.file_exists("{}\{}".format(self.sharex_path, self.SHAREX_EXE)):
> >             self.err("Could not find ShareX executable in the provided path: ", self.sharex_path)
> > 
> >         self.sharex_userpath = settings.get_stripped("user_path", "main", self.DEFAULT_SHAREXUSER_PATH)  
> > ```
> 
> I can confirm that modification is successful - I directly modified de _py_ inside keypirinha package, and it works. @Fuhrmann, could you update the project? If you want, we can create a pull request for you.

Could you send a PR if you are still interested? I'm not in my Windows machine so I need to setup a VM.

**Comment by Fuhrmann** [comment]
Hey, https://github.com/Fuhrmann/keypirinha-sharex/commit/79d1ce93b737d0950ce720c904d96f938e810277 should fix this. Thanks all!

New release:

https://github.com/Fuhrmann/keypirinha-sharex/releases/tag/1.0.2

**Comment by sorashadow** [comment]
Thanks o/

**Comment by AlesRFK** [comment]
Still can't use the PATH variables but thank to you ShareX-portable works!
![image](https://user-images.githubusercontent.com/13176180/81500835-0783f800-92d5-11ea-8e80-64880b93144f.png)

**Comment by AbhishekTripathi** [comment]
This plugin is still broken for portable sharex installs. My path setting is not getting applied. I tried with path values both quoted and unquoted.
```
[main]
path = D:\dropbox\tools\ShareX
user_path = D:\dropbox\tools\ShareX\ShareX
```

![image](https://user-images.githubusercontent.com/1847545/99192104-54a7c180-2771-11eb-81eb-7dbe8beb3e39.png)

**Comment by brgrvrm** [comment]
Same thing here. Plugin path config not working for portable version of ShareX.

**Comment by AlesRFK** [comment]
> Same thing here. Plugin path config not working for portable version of ShareX.

I've stoped using it when I've managed to fix this issue. But I can confirm that now (maybe after some updates) program have problems finding the right files.

**Comment by egabrum** [comment]
Sorry to add a comment just to say "me too"... but can we at least reopen this issue? It's clearly not fixed yet. Thanks.
